VERTCOIN_DASHBOARD_LOCATION=/var/www/vertcoin-dashboard.com
INSTALL_LOC=/home/checkout/vertcoin-dash/

default:
	@cd $(INSTALL_LOC); \
		npm install; \
		grunt
	@mkdir -p $(VERTCOIN_DASHBOARD_LOCATION)/public_html
	@cd $(INSTALL_LOC); \
		rsync -qavI --exclude 'public/assets/tpl' --exclude 'public/assets/less' --exclude 'public/src' ./public
